package moduls;
// Generated 10.03.2021 11:07:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clas generated by hbm2java
 */
@Entity
@Table(name="clas"
    ,catalog="dndthings2"
)
public class Clas  implements java.io.Serializable {


     private Integer idClass;
     private String name;
     private String hpDice;
     private Set<Magicclass> magicclasses = new HashSet<Magicclass>(0);

    public Clas() {
    }

    public Clas(String name, String hpDice, Set<Magicclass> magicclasses) {
       this.name = name;
       this.hpDice = hpDice;
       this.magicclasses = magicclasses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idClass", unique=true, nullable=false)
    public Integer getIdClass() {
        return this.idClass;
    }
    
    public void setIdClass(Integer idClass) {
        this.idClass = idClass;
    }

    
    @Column(name="Name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="HpDice", length=5)
    public String getHpDice() {
        return this.hpDice;
    }
    
    public void setHpDice(String hpDice) {
        this.hpDice = hpDice;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clas")
    public Set<Magicclass> getMagicclasses() {
        return this.magicclasses;
    }
    
    public void setMagicclasses(Set<Magicclass> magicclasses) {
        this.magicclasses = magicclasses;
    }




}


