package moduls;
// Generated 24.02.2021 14:05:56 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Magic generated by hbm2java
 */
@Entity
@Table(name="magic"
    ,catalog="dndthings2"
)
public class Magic  implements java.io.Serializable {


     private Integer idMagic;
     private School school;
     private String name;
     private Integer lvl;
     private String custTime;
     private String distance;
     private String components;
     private String duration;
     private String damage;
     private String about;

    public Magic() {
    }

    public Magic(String name, Integer lvl, School school, String custTime, String distance, String components, String duration, String damage, String about) {       
       this.name = name;
       this.lvl = lvl;
       this.school = school;       
       this.custTime = custTime;
       this.distance = distance;
       this.components = components;
       this.duration = duration;
       this.damage = damage;
       this.about = about;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idMagic", unique=true, nullable=false)
    public Integer getIdMagic() {
        return this.idMagic;
    }
    
    public void setIdMagic(Integer idMagic) {
        this.idMagic = idMagic;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idSchool")
    public School getSchool() {
        return this.school;
    }
    
    public void setSchool(School school) {
        this.school = school;
    }

    
    @Column(name="Name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Lvl")
    public Integer getLvl() {
        return this.lvl;
    }
    
    public void setLvl(Integer lvl) {
        this.lvl = lvl;
    }

    
    @Column(name="CustTime", length=100)
    public String getCustTime() {
        return this.custTime;
    }
    
    public void setCustTime(String custTime) {
        this.custTime = custTime;
    }

    
    @Column(name="Distance", length=20)
    public String getDistance() {
        return this.distance;
    }
    
    public void setDistance(String distance) {
        this.distance = distance;
    }

    
    @Column(name="Components", length=300)
    public String getComponents() {
        return this.components;
    }
    
    public void setComponents(String components) {
        this.components = components;
    }

    
    @Column(name="Duration", length=45)
    public String getDuration() {
        return this.duration;
    }
    
    public void setDuration(String duration) {
        this.duration = duration;
    }

    
    @Column(name="Damage", length=20)
    public String getDamage() {
        return this.damage;
    }
    
    public void setDamage(String damage) {
        this.damage = damage;
    }

    
    @Column(name="About", length=20000)
    public String getAbout() {
        return this.about;
    }
    
    public void setAbout(String about) {
        this.about = about;
    }




}


