package moduls;
// Generated 10.03.2021 11:07:24 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Magicclass generated by hbm2java
 */
@Entity
@Table(name="magicclass"
    ,catalog="dndthings2"
)
public class Magicclass  implements java.io.Serializable {


     private Integer idMagicClass;
     private Clas clas;
     private Magic magic;

    public Magicclass() {
    }

    public Magicclass(Clas clas, Magic magic) {
       this.clas = clas;
       this.magic = magic;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idMagicClass", unique=true, nullable=false)
    public Integer getIdMagicClass() {
        return this.idMagicClass;
    }
    
    public void setIdMagicClass(Integer idMagicClass) {
        this.idMagicClass = idMagicClass;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idClass")
    public Clas getClas() {
        return this.clas;
    }
    
    public void setClas(Clas clas) {
        this.clas = clas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idMagic")
    public Magic getMagic() {
        return this.magic;
    }
    
    public void setMagic(Magic magic) {
        this.magic = magic;
    }




}


